/** Starter vocabularies (Appendix A) — everything here is editable via the vocabulary manager
 * (Settings → Vocabularies, §2.5). Each value's AI hint is its English name unless another hint
 * is given, so most entries omit `aiHint`. Tags start empty (not seeded). */
export interface VocabularyEntry {
  name: string;
  aiHint?: string;
}

export const STARTER_TYPES: VocabularyEntry[] = [
  { name: 'Poster' },
  { name: 'Illustration' },
  { name: 'Photography' },
  { name: 'Typography' },
  { name: 'Logo & branding' },
  { name: 'Packaging' },
  { name: 'Editorial & book' },
  { name: 'UI & web' },
  { name: 'Motion' },
  { name: 'Painting' },
  { name: 'Drawing & sketch' },
  { name: 'Sculpture & 3D' },
  { name: 'Architecture' },
  { name: 'Interior' },
  { name: 'Fashion' },
  { name: 'Textile & pattern' },
  { name: 'Product & object' },
  { name: 'Film still' },
  { name: 'Collage' },
  { name: 'Signage & wayfinding' },
  { name: 'Other' },
];

export const STARTER_VIBES: VocabularyEntry[] = [
  { name: 'Dreamy' },
  { name: 'Bold' },
  { name: 'Playful' },
  { name: 'Calm' },
  { name: 'Melancholic' },
  { name: 'Nostalgic' },
  { name: 'Futuristic' },
  { name: 'Mysterious' },
  { name: 'Eerie' },
  { name: 'Romantic' },
  { name: 'Energetic' },
  { name: 'Minimal' },
  { name: 'Chaotic' },
  { name: 'Cozy' },
  { name: 'Elegant' },
  { name: 'Raw' },
  { name: 'Whimsical' },
  { name: 'Dramatic' },
  { name: 'Ethereal' },
  { name: 'Gritty' },
  { name: 'Sensual' },
  { name: 'Cheerful' },
  { name: 'Dark' },
  { name: 'Serene' },
];

export const STARTER_MOVEMENTS: VocabularyEntry[] = [
  { name: 'Arts and Crafts' },
  { name: 'Art Nouveau' },
  { name: 'Art Deco' },
  { name: 'Bauhaus' },
  { name: 'Constructivism' },
  { name: 'De Stijl' },
  { name: 'Futurism' },
  { name: 'Dada' },
  { name: 'Surrealism' },
  { name: 'Expressionism' },
  { name: 'Cubism' },
  { name: 'Impressionism' },
  {
    name: 'Swiss Style',
    aiHint: 'Swiss International Typographic Style, grid layout, sans-serif',
  },
  { name: 'Mid-century Modern' },
  { name: 'Pop Art' },
  { name: 'Op Art' },
  { name: 'Psychedelic' },
  { name: 'Minimalism' },
  { name: 'Brutalism' },
  { name: 'Postmodernism' },
  { name: 'Memphis', aiHint: 'Memphis Group design, 1980s, bold geometric patterns' },
  { name: 'Punk' },
  { name: 'Grunge' },
  { name: 'Y2K', aiHint: 'Y2K aesthetic, chrome, early 2000s' },
  { name: 'Vaporwave' },
  { name: 'Ukiyo-e' },
  { name: 'Japonisme' },
  { name: 'Baroque' },
  { name: 'Renaissance' },
  { name: 'Street art' },
  { name: 'Contemporary' },
];
